#ifndef BRAMBLE_MESH_TASK_H
#define BRAMBLE_MESH_TASK_H

#include "identity.h"
#include "routing.h"
#include "dedup.h"
#include "freq_plan.h"
#include "channel_key.h"
#include "channel_msg.h"
#include "public_channel.h"
#include "airtime_budget.h"
#include "traffic_debug.h"
#include "location.h"
#include "delivery_event_ring.h"

#define BRAMBLE_NODE_NAME_MAX 32

/* Shared mesh state — protected by mutex, read by UI task */
typedef struct {
    neighbor_table_t neighbors;
    uint32_t beacon_tx_count;
    uint32_t beacon_rx_count;
    uint32_t packets_tx;
    uint32_t packets_rx;
    bool radio_ok;
    int16_t last_rx_rssi;
    int8_t last_rx_snr;
    airtime_budget_t airtime;
} mesh_shared_state_t;

/**
 * Start the mesh task on CPU1.
 * Initializes radio, begins beacon TX/RX.
 */
void mesh_task_start(bramble_identity_t* identity);

/**
 * Get a snapshot of shared state (thread-safe).
 */
void mesh_get_state(mesh_shared_state_t* out);

/**
 * Send a broadcast message on the public channel.
 * Returns 0 on success.
 */
int mesh_send_broadcast(const uint8_t* data, size_t len);

/** Last successful broadcast packet id generated by send path (0 if none). */
uint32_t mesh_get_last_broadcast_id(void);

/** Broadcast delivery telemetry mode. */
typedef enum {
    BROADCAST_TELEMETRY_OFF = 0,
    BROADCAST_TELEMETRY_RECIPIENT_ONLY = 1,
    BROADCAST_TELEMETRY_PATH_SAMPLED = 2,
} broadcast_telemetry_mode_t;

void mesh_set_broadcast_telemetry_mode(broadcast_telemetry_mode_t mode);
broadcast_telemetry_mode_t mesh_get_broadcast_telemetry_mode(void);

/* Exposed for protocol/RPC testing and used by delivery receipt handling. */
void mesh_emit_broadcast_delivery_notification(uint32_t src_addr, uint32_t broadcast_id,
                                               int8_t rssi_at_dest, uint8_t hop_count,
                                               const uint32_t* relay_path);

/* Delivery-event replay sync support */
bool mesh_supports_delivery_event_sync(void);
uint32_t mesh_delivery_events_latest_seq(void);
size_t mesh_delivery_events_list_since(uint32_t since_event_seq, delivery_event_record_t* out,
                                       size_t out_max);

/**
 * Send an encrypted message on a specific channel index.
 * Returns packet_id (>0) on success, 0 on failure.
 */
uint32_t mesh_send_channel(int channel_idx, uint32_t dest_addr, const uint8_t* data, size_t len);

/**
 * Send an encrypted message to a specific address.
 * Uses public channel for now (DM encryption requires key exchange).
 * Returns packet_id (>0) on success, 0 on failure.
 */
uint32_t mesh_send_message(uint32_t dest_addr, const uint8_t* data, size_t len);

/**
 * Send a dedicated location packet (PKT_TYPE_LOCATION) to a single destination.
 * Returns packet_id (>0) on success, 0 on failure.
 */
uint32_t mesh_send_location_packet(uint32_t dest_addr, const bramble_position_t* pos, uint8_t tier);

/**
 * Schedule a system reboot after delay_ms milliseconds.
 * Uses a one-shot FreeRTOS timer; safe to call from any task.
 */
void mesh_reboot_delayed(int delay_ms);

/**
 * Get a snapshot of the routing table (thread-safe).
 */
void mesh_get_routes(routing_table_t* out);

/**
 * Get a snapshot of the location manager state (thread-safe).
 */
void mesh_get_location_state(location_manager_t* out);

/**
 * Add a channel to the mesh. Returns channel index or -1 on error.
 */
int mesh_add_channel(const char* name, const uint8_t* psk, size_t psk_len);

/**
 * Remove a channel by index. Returns 0 on success.
 * Cannot remove index 0 (public channel).
 */
int mesh_remove_channel(int index);

/**
 * Get channel count.
 */
int mesh_get_channel_count(void);

/**
 * Get channel name by index (returns NULL if unavailable).
 */
const char* mesh_get_channel_name(int index);

/**
 * Returns whether channel is PSK-protected and current key epoch.
 * Returns 0 on success, -1 for invalid index.
 */
int mesh_get_channel_security(int index, bool* has_psk, uint16_t* epoch);

/**
 * Set default channel index for unicast send routing.
 * Broadcast always uses the public channel (index 0).
 * Returns 0 on success.
 */
int mesh_set_default_channel(int index);

/**
 * Send a network reachability probe (broadcast).
 * Returns the probe packet ID.
 */
uint32_t mesh_send_probe(void);

/**
 * Enable/disable mailbox (store-and-forward for offline neighbors).
 */
void mesh_set_node_name(const char* name);
int mesh_set_node_name_persist(const char* name);
void mesh_set_mailbox(bool enabled);
bool mesh_get_mailbox(void);

/**
 * Enable/disable the flood transport (Flooding F1, Task 1): when on, a
 * received unicast DATA not addressed to us is relayed through the same
 * multi-hop flood engine broadcast DATA already uses (channel_flood_decide +
 * s_flood_dedup), instead of the reactive route-lookup forward
 * (forward_data_packet). Default false (reactive unchanged); NVS-persisted
 * so the setting survives reboot, same pattern as mesh_set_mailbox above.
 */
void mesh_set_flood_transport(bool enabled);
bool mesh_get_flood_transport(void);

/**
 * Set/get the flood-transport origination hop budget (Flooding F1 finalize).
 * mesh_set_flood_hop_limit clamps to [FLOOD_HOP_LIMIT_MIN, FLOOD_HOP_LIMIT_CEIL]
 * and stores the clamped value (read it back with mesh_get_flood_hop_limit).
 * Under s_flood_transport this is the hop_limit a freshly-originated flood DATA
 * and its flooded-ACK are stamped with; the reactive path (ROUTE_HOP_LIMIT_MAX)
 * is unaffected. Default FLOOD_HOP_LIMIT_DEFAULT (8); NVS-persisted by the RPC
 * setter, same pattern as mesh_set_flood_transport above.
 */
void mesh_set_flood_hop_limit(uint32_t hops);
uint8_t mesh_get_flood_hop_limit(void);

/**
 * Get the current node name (returns NULL if not set).
 */
const char* mesh_get_node_name(void);

/* Network wall clock for display. Returns true and writes epoch ms only
 * when mesh timesync is synchronized. */
bool mesh_get_network_time_ms(int64_t* out_ms);

/**
 * Get the local identity address and public key.
 * Returns 0 on success, -1 if identity not ready.
 */
int mesh_get_identity(uint32_t* addr_out, uint8_t pubkey_out[32]);

/**
 * Per-node identity Phase 4 diagnostics: current verified-pin count and
 * the impersonation-signal counters (TOFU conflicts, delivered
 * attestations with invalid Ed25519 sigs, delivered attestations whose
 * src_addr did not match their key's derived address). The trust-anchor
 * campaign (P2) adds two more: unendorsed (delivered attestations refused
 * on an anchored node for a missing/invalid endorsement cert) and expired
 * (refused for a cert past the synced wall clock). Any out-pointer may be
 * NULL. Lock-free word reads; values are diagnostics-grade.
 */
void mesh_get_identity_pin_stats(uint32_t* pins, uint32_t* conflicts, uint32_t* sig_failures,
                                 uint32_t* addr_mismatches, uint32_t* unendorsed,
                                 uint32_t* expired);

/**
 * Per-peer SAS + verification state (DM forward-secrecy + SAS, Task 7.5): the
 * single accessor the pager UI (Task 8) and webapp RPC (Task 9) both consume.
 * Fills sas_out with the identity SAS between this node and addr, plus the
 * peer's persisted verified bit and RAM-only key_changed warning flag.
 * Returns false (leaving the outputs untouched) if there is no pin for addr
 * or the SAS derivation fails. sas_out is a 7-digit string plus NUL.
 */
bool mesh_get_peer_verification(uint32_t addr, char sas_out[8], bool* verified, bool* key_changed);

/**
 * Cheap verified/key-changed flags for a peer with no SAS derivation (for
 * list glyphs, which redraw every neighbor on every screen refresh and never
 * display the SAS itself). Returns false (flags cleared) if there is no pin.
 */
bool mesh_get_peer_verify_flags(uint32_t addr, bool* verified, bool* key_changed);

/**
 * Sets or clears a peer's SAS-verified state and persists it (DM
 * forward-secrecy + SAS, Task 8): the mesh accessor the pager confirm action
 * and Task 9's RPC both go through, never identity_store directly. When
 * verifying, records the current identity SAS with the pin, which also
 * dismisses a pending key-change warning. When un-verifying, only clears the
 * verified bit; a deliberate un-verify is not a key change and must not raise
 * one. Returns false if there is no pin for addr (cannot verify an unpinned
 * peer).
 */
bool mesh_set_peer_verified(uint32_t addr, bool verified);

/*
 * Trust-anchor campaign (P2): push a newly provisioned fleet anchor into the
 * live pin store so a runtime bramble.setAnchor takes effect on the pin gate
 * without a reboot. anchor_pub is the fleet anchor's Ed25519 public key.
 */
void mesh_set_pin_anchor(const uint8_t anchor_pub[BRAMBLE_ED25519_PUBKEY_SIZE]);

/**
 * Get a peer's name from the neighbor table (returns NULL if not found or no name).
 */
const char* mesh_get_peer_name(uint32_t addr);

/**
 * Get channel count and default channel index (thread-safe).
 * If default_idx is not NULL, sets it to the current default channel index.
 * Returns the number of channels.
 */
int mesh_get_channel_info(int* default_idx);

/**
 * Get traffic debug instance (for RPC query access).
 */
traffic_debug_t* mesh_get_traffic_debug(void);

/**
 * Set traffic debug runtime configuration and persist to NVS.
 */
void mesh_traffic_debug_set_config(bool enabled, bool include_tx, bool include_rx,
                                   uint8_t sample_rate);

/**
 * Get traffic debug runtime configuration.
 */
void mesh_traffic_debug_get_config(bool* enabled, bool* include_tx, bool* include_rx,
                                   uint8_t* sample_rate);

/**
 * Load traffic debug config from NVS at startup.
 */
void mesh_traffic_debug_load_config(void);

/**
 * Adaptive beacon interval policy mode
 */
typedef enum {
    BEACON_MODE_FIXED = 0,    /* Fixed 60s interval (default, backward-compatible) */
    BEACON_MODE_ADAPTIVE = 1, /* Adaptive mode based on mesh conditions */
} beacon_policy_mode_t;

/**
 * Adaptive beacon interval configuration
 */
typedef struct {
    bool enabled;              /* Enable adaptive policy (default: false) */
    beacon_policy_mode_t mode; /* Policy mode */
    uint32_t base_interval_ms; /* Base interval (default: 60000) */
    uint32_t min_interval_ms;  /* Minimum interval (default: 30000) */
    uint32_t max_interval_ms;  /* Maximum interval (default: 120000) */
    uint8_t dense_threshold;   /* Neighbor count for dense mode (default: 10) */
    uint8_t churn_threshold;   /* Neighbor changes/min for churn (default: 3) */
    uint32_t churn_window_ms;  /* Time window for churn detection (default: 60000) */
} beacon_policy_config_t;

/**
 * Adaptive beacon interval runtime status
 */
typedef struct {
    beacon_policy_mode_t active_mode; /* Currently active mode */
    uint32_t current_interval_ms;     /* Current beacon interval */
    uint8_t neighbor_count;           /* Current neighbor count */
    uint8_t churn_events;             /* Churn events in current window */
    uint32_t last_transition_ms;      /* Last mode transition timestamp */
    bool in_backoff;                  /* Currently in dense/churn backoff */
} beacon_policy_status_t;

/**
 * Set beacon policy configuration and persist to NVS.
 * Returns 0 on success.
 */
int mesh_set_beacon_policy(const beacon_policy_config_t* config);

/**
 * Get current beacon policy configuration.
 */
void mesh_get_beacon_policy(beacon_policy_config_t* config);

/**
 * Get beacon policy runtime status.
 */
void mesh_get_beacon_status(beacon_policy_status_t* status);

/**
 * Load beacon policy config from NVS at startup.
 */
void mesh_beacon_policy_load_config(void);

/* Re-derive the beacon HMAC subkey from the current network key. Call after
 * a runtime setNetworkKey so beacons pick up a newly provisioned key without
 * a reboot (routing/ACK MACs already re-read the key per call). */
void mesh_rederive_beacon_key(void);

/* Trigger a fresh identity attestation now (budget-gated). Called after a
 * runtime setEndorsement so the node re-announces with its new cert without
 * waiting for the next periodic attestation (trust-anchor campaign, P1);
 * mirrors the attest-on-address/key-change hook. */
void mesh_trigger_attestation(void);

#endif
