#ifndef BRAMBLE_MESH_TASK_H
#define BRAMBLE_MESH_TASK_H

#include "identity.h"
#include "routing.h"
#include "dedup.h"
#include "freq_plan.h"
#include "channel_key.h"
#include "channel_msg.h"
#include "public_channel.h"
#include "airtime_budget.h"
#include "traffic_debug.h"
#include "location.h"
#include "delivery_event_ring.h"

#define BRAMBLE_NODE_NAME_MAX 32

/* Shared mesh state — protected by mutex, read by UI task */
typedef struct {
    neighbor_table_t neighbors;
    uint32_t         beacon_tx_count;
    uint32_t         beacon_rx_count;
    uint32_t         packets_tx;
    uint32_t         packets_rx;
    bool             radio_ok;
    int16_t          last_rx_rssi;
    int8_t           last_rx_snr;
    airtime_budget_t airtime;
} mesh_shared_state_t;

/**
 * Start the mesh task on CPU1.
 * Initializes radio, begins beacon TX/RX.
 */
void mesh_task_start(bramble_identity_t *identity);

/**
 * Get a snapshot of shared state (thread-safe).
 */
void mesh_get_state(mesh_shared_state_t *out);

/**
 * Send a broadcast message on the public channel.
 * Returns 0 on success.
 */
int mesh_send_broadcast(const uint8_t *data, size_t len);

/** Last successful broadcast packet id generated by send path (0 if none). */
uint32_t mesh_get_last_broadcast_id(void);

/** Broadcast delivery telemetry mode. */
typedef enum {
    BROADCAST_TELEMETRY_OFF = 0,
    BROADCAST_TELEMETRY_RECIPIENT_ONLY = 1,
    BROADCAST_TELEMETRY_PATH_SAMPLED = 2,
} broadcast_telemetry_mode_t;

void mesh_set_broadcast_telemetry_mode(broadcast_telemetry_mode_t mode);
broadcast_telemetry_mode_t mesh_get_broadcast_telemetry_mode(void);

/* Exposed for protocol/RPC testing and used by delivery receipt handling. */
void mesh_emit_broadcast_delivery_notification(uint32_t src_addr,
                                               uint32_t broadcast_id,
                                               int8_t rssi_at_dest,
                                               uint8_t hop_count,
                                               const uint32_t *relay_path);

/* Delivery-event replay sync support */
bool mesh_supports_delivery_event_sync(void);
uint32_t mesh_delivery_events_latest_seq(void);
size_t mesh_delivery_events_list_since(uint32_t since_event_seq,
                                       delivery_event_record_t *out,
                                       size_t out_max);

/**
 * Send an encrypted message on a specific channel index.
 * Returns packet_id (>0) on success, 0 on failure.
 */
uint32_t mesh_send_channel(int channel_idx, uint32_t dest_addr, const uint8_t *data, size_t len);

/**
 * Send an encrypted message to a specific address.
 * Uses public channel for now (DM encryption requires key exchange).
 * Returns packet_id (>0) on success, 0 on failure.
 */
uint32_t mesh_send_message(uint32_t dest_addr, const uint8_t *data, size_t len);

/**
 * Send a dedicated location packet (PKT_TYPE_LOCATION) to a single destination.
 * Returns packet_id (>0) on success, 0 on failure.
 */
uint32_t mesh_send_location_packet(uint32_t dest_addr,
                                   const bramble_position_t *pos,
                                   uint8_t tier);

/**
 * Schedule a system reboot after delay_ms milliseconds.
 * Uses a one-shot FreeRTOS timer; safe to call from any task.
 */
void mesh_reboot_delayed(int delay_ms);

/**
 * Get a snapshot of the routing table (thread-safe).
 */
void mesh_get_routes(routing_table_t *out);

/**
 * Get a snapshot of the location manager state (thread-safe).
 */
void mesh_get_location_state(location_manager_t *out);

/**
 * Add a channel to the mesh. Returns channel index or -1 on error.
 */
int mesh_add_channel(const char *name, const uint8_t *psk, size_t psk_len);

/**
 * Remove a channel by index. Returns 0 on success.
 * Cannot remove index 0 (public channel).
 */
int mesh_remove_channel(int index);

/**
 * Get channel count.
 */
int mesh_get_channel_count(void);

/**
 * Get channel name by index (returns NULL if unavailable).
 */
const char *mesh_get_channel_name(int index);

/**
 * Returns whether channel is PSK-protected and current key epoch.
 * Returns 0 on success, -1 for invalid index.
 */
int mesh_get_channel_security(int index, bool *has_psk, uint16_t *epoch);

/**
 * Set default channel index for unicast send routing.
 * Broadcast always uses the public channel (index 0).
 * Returns 0 on success.
 */
int mesh_set_default_channel(int index);

/**
 * Send a network reachability probe (broadcast).
 * Returns the probe packet ID.
 */
uint32_t mesh_send_probe(void);

/**
 * Enable/disable mailbox (store-and-forward for offline neighbors).
 */
void mesh_set_node_name(const char *name);
int  mesh_set_node_name_persist(const char *name);
void mesh_set_mailbox(bool enabled);
bool mesh_get_mailbox(void);

/**
 * Get the current node name (returns NULL if not set).
 */
const char *mesh_get_node_name(void);

/**
 * Get the local identity address and public key.
 * Returns 0 on success, -1 if identity not ready.
 */
int mesh_get_identity(uint32_t *addr_out, uint8_t pubkey_out[32]);

/**
 * Get a peer's name from the neighbor table (returns NULL if not found or no name).
 */
const char *mesh_get_peer_name(uint32_t addr);

/**
 * Get channel count and default channel index (thread-safe).
 * If default_idx is not NULL, sets it to the current default channel index.
 * Returns the number of channels.
 */
int mesh_get_channel_info(int *default_idx);

/**
 * Get traffic debug instance (for RPC query access).
 */
traffic_debug_t *mesh_get_traffic_debug(void);

/**
 * Set traffic debug runtime configuration and persist to NVS.
 */
void mesh_traffic_debug_set_config(bool enabled, bool include_tx, bool include_rx, uint8_t sample_rate);

/**
 * Get traffic debug runtime configuration.
 */
void mesh_traffic_debug_get_config(bool *enabled, bool *include_tx, bool *include_rx, uint8_t *sample_rate);

/**
 * Load traffic debug config from NVS at startup.
 */
void mesh_traffic_debug_load_config(void);

/**
 * Adaptive beacon interval policy mode
 */
typedef enum {
    BEACON_MODE_FIXED = 0,      /* Fixed 60s interval (default, backward-compatible) */
    BEACON_MODE_ADAPTIVE = 1,   /* Adaptive mode based on mesh conditions */
} beacon_policy_mode_t;

/**
 * Adaptive beacon interval configuration
 */
typedef struct {
    bool                enabled;            /* Enable adaptive policy (default: false) */
    beacon_policy_mode_t mode;              /* Policy mode */
    uint32_t            base_interval_ms;   /* Base interval (default: 60000) */
    uint32_t            min_interval_ms;    /* Minimum interval (default: 30000) */
    uint32_t            max_interval_ms;    /* Maximum interval (default: 120000) */
    uint8_t             dense_threshold;    /* Neighbor count for dense mode (default: 10) */
    uint8_t             churn_threshold;    /* Neighbor changes/min for churn (default: 3) */
    uint32_t            churn_window_ms;    /* Time window for churn detection (default: 60000) */
} beacon_policy_config_t;

/**
 * Adaptive beacon interval runtime status
 */
typedef struct {
    beacon_policy_mode_t active_mode;       /* Currently active mode */
    uint32_t            current_interval_ms; /* Current beacon interval */
    uint8_t             neighbor_count;      /* Current neighbor count */
    uint8_t             churn_events;        /* Churn events in current window */
    uint32_t            last_transition_ms;  /* Last mode transition timestamp */
    bool                in_backoff;          /* Currently in dense/churn backoff */
} beacon_policy_status_t;

/**
 * Set beacon policy configuration and persist to NVS.
 * Returns 0 on success.
 */
int mesh_set_beacon_policy(const beacon_policy_config_t *config);

/**
 * Get current beacon policy configuration.
 */
void mesh_get_beacon_policy(beacon_policy_config_t *config);

/**
 * Get beacon policy runtime status.
 */
void mesh_get_beacon_status(beacon_policy_status_t *status);

/**
 * Load beacon policy config from NVS at startup.
 */
void mesh_beacon_policy_load_config(void);

#endif
