/* Auto-generated by tools/convert_logo.py. Do not edit manually. */

#ifndef IMG_BRAMBLE_LOGO_H
#define IMG_BRAMBLE_LOGO_H

#include "lvgl.h"

/* The splash logo, RGB565A8, flash-resident. */
extern const lv_image_dsc_t img_bramble_logo;

/* Fully transparent padding the generator cropped off each side. Add these
 * back as layout margins to reproduce the uncropped image's footprint. */
#define IMG_BRAMBLE_LOGO_MARGIN_X 16
#define IMG_BRAMBLE_LOGO_MARGIN_Y 13

/* The nominal (uncropped) square the art was designed against. */
#define IMG_BRAMBLE_LOGO_NOMINAL 100

#endif /* IMG_BRAMBLE_LOGO_H */
