#!/usr/bin/env python3
"""Convert the Bramble logo SVG/PNG to an LVGL-compatible C array (RGB565 + alpha).

Outputs a 100x100-nominal splash logo for the T-Deck Plus (320x240 display) as a
C source file holding an `lv_image_dsc_t`.

The logo art does not fill its square: roughly three quarters of the source
pixels are fully transparent padding. Storing that padding costs flash and buys
nothing, so the encoder crops to the alpha bounding box, symmetrically, so the
art stays centred, and reports the margins it removed. `scr_splash.c` adds those
margins back as LVGL style margins, which reproduces the original layout
footprint exactly while storing only the pixels that are actually drawn.

The format stays LV_COLOR_FORMAT_RGB565A8 on purpose. For an
LV_IMAGE_SRC_VARIABLE source, LVGL 9.2 draws uncompressed non-indexed formats
straight from flash (lv_bin_decoder.c "In case of uncompressed formats the image
stored in the ROM/RAM. So simply give its pointer"). Indexed formats and the
LV_IMAGE_FLAGS_COMPRESSED path both allocate a full-size decode buffer in RAM
instead, which would trade flash for a scarcer resource. See the PR for #113.

Source: bramble/webapp/public/bramble-logo.png (Bramble project, MIT license)
"""

import sys
from pathlib import Path

try:
    from PIL import Image
    import cairosvg
    import io
except ImportError:
    print("pip install pillow cairosvg")
    sys.exit(1)


def svg_to_png(svg_path, size):
    """Render SVG to PNG at given size."""
    png_data = cairosvg.svg2png(url=str(svg_path), output_width=size, output_height=size)
    return Image.open(io.BytesIO(png_data)).convert("RGBA")


def symmetric_alpha_crop(img):
    """Crop fully transparent padding, keeping the art centred in its box.

    Returns (cropped_image, margin_x, margin_y). Cropping the raw alpha bounding
    box would shift the art if the padding is lopsided, so take the smaller
    margin on each axis and remove that much from both sides. The caller adds
    the margins back as layout margins, so the rendered result is identical.
    """
    bbox = img.getbbox()
    if bbox is None:
        return img, 0, 0

    left, top, right, bottom = bbox
    w, h = img.size

    margin_x = min(left, w - right)
    margin_y = min(top, h - bottom)

    return img.crop((margin_x, margin_y, w - margin_x, h - margin_y)), margin_x, margin_y


def rgba_to_rgb565_alpha(img):
    """Convert RGBA image to RGB565 + 8-bit alpha arrays."""
    pixels = list(img.getdata())
    rgb565 = []
    alpha = []
    for r, g, b, a in pixels:
        # RGB565: RRRRR GGGGGG BBBBB
        val = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        rgb565.append(val)
        alpha.append(a)
    return rgb565, alpha


def write_c_array(rgb565, alpha, width, height, name, out_path, margin_x, margin_y, nominal):
    """Write the LVGL image C source.

    LVGL v9 LV_COLOR_FORMAT_RGB565A8 is PLANAR:
      - First: all RGB565 pixels (width * height * 2 bytes)
      - Then:  all alpha values (width * height bytes)
    stride = width * 2 (bytes per row, RGB565 only)

    The byte arrays are wrapped in clang-format off/on. Without it the repo
    clang-format config reflows this file to one byte per line, which is what
    made the old version 30022 lines long.
    """
    stride = width * 2
    data_size = width * height * 3

    with open(out_path, "w") as f:
        f.write("/* Auto-generated by tools/convert_logo.py from webapp/public/bramble-logo.png. */\n")
        f.write("/* Do not edit manually: re-run the generator instead. */\n")
        f.write("/* Flash-resident: static const keeps this in .rodata (flash, not RAM). */\n\n")

        f.write('#include "lvgl.h"\n')
        f.write('#include "img_bramble_logo.h"\n\n')

        f.write(f"/* {width}x{height} px RGB565A8, {data_size} bytes in flash.\n")
        f.write(f" * Cropped from a nominal {nominal}x{nominal} box by removing {margin_x} px of\n")
        f.write(f" * fully transparent padding per side horizontally and {margin_y} px vertically.\n")
        f.write(" * scr_splash.c adds those back as layout margins, so the on-screen result is\n")
        f.write(f" * identical to the uncropped {nominal}x{nominal} image. */\n")

        f.write("/* clang-format off */\n")
        f.write(f"static const uint8_t {name}_map[] __attribute__((aligned(4))) = {{\n")

        f.write(f"    /* RGB565 pixel data ({width * height * 2} bytes, stride={stride}) */\n")
        flat = []
        for px in rgb565:
            flat.append(px & 0xFF)
            flat.append((px >> 8) & 0xFF)
        for i in range(0, len(flat), 16):
            f.write("    " + " ".join(f"0x{b:02x}," for b in flat[i:i + 16]) + "\n")

        f.write(f"    /* Alpha data ({width * height} bytes) */\n")
        for i in range(0, len(alpha), 16):
            f.write("    " + " ".join(f"0x{a:02x}," for a in alpha[i:i + 16]) + "\n")

        f.write("};\n")
        f.write("/* clang-format on */\n\n")

        f.write(f"const lv_image_dsc_t {name} = {{\n")
        f.write("    .header =\n")
        f.write("        {\n")
        f.write("            .cf = LV_COLOR_FORMAT_RGB565A8,\n")
        f.write(f"            .w = {width},\n")
        f.write(f"            .h = {height},\n")
        f.write(f"            .stride = {stride},\n")
        f.write("        },\n")
        f.write(f"    .data_size = {data_size},\n")
        f.write(f"    .data = {name}_map,\n")
        f.write("};\n")

    print(f"Written {out_path} ({width}x{height}, {data_size} bytes, stride={stride})")


def write_c_header(name, out_path, margin_x, margin_y, nominal):
    """Write the header declaring the descriptor and the layout margins."""
    guard = f"{name.upper()}_H"
    with open(out_path, "w") as f:
        f.write("/* Auto-generated by tools/convert_logo.py. Do not edit manually. */\n\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write('#include "lvgl.h"\n\n')
        f.write("/* The splash logo, RGB565A8, flash-resident. */\n")
        f.write(f"extern const lv_image_dsc_t {name};\n\n")
        f.write("/* Fully transparent padding the generator cropped off each side. Add these\n")
        f.write(" * back as layout margins to reproduce the uncropped image's footprint. */\n")
        f.write(f"#define {name.upper()}_MARGIN_X {margin_x}\n")
        f.write(f"#define {name.upper()}_MARGIN_Y {margin_y}\n\n")
        f.write("/* The nominal (uncropped) square the art was designed against. */\n")
        f.write(f"#define {name.upper()}_NOMINAL {nominal}\n\n")
        f.write(f"#endif /* {guard} */\n")
    print(f"Written {out_path}")


def main():
    base = Path(__file__).parent.parent
    # Prefer the full webapp logo (512x512 RGBA) over the small favicon SVG
    png_primary = base / "webapp" / "public" / "bramble-logo.png"
    svg_path = base / "webapp" / "public" / "favicon.svg"
    png_fallback = base / "assets" / "bramble-logo.png"

    size = 100  # 100x100 nominal for splash on the 320x240 T-Deck Plus

    if png_primary.exists():
        print(f"Resizing PNG: {png_primary}")
        img = Image.open(png_primary).convert("RGBA").resize((size, size), Image.LANCZOS)
    elif svg_path.exists():
        print(f"Converting SVG: {svg_path}")
        img = svg_to_png(svg_path, size)
    elif png_fallback.exists():
        print(f"Resizing PNG: {png_fallback}")
        img = Image.open(png_fallback).convert("RGBA").resize((size, size), Image.LANCZOS)
    else:
        print("No logo source found!")
        sys.exit(1)

    # Also save a preview PNG of the uncropped nominal image
    preview_path = base / "assets" / f"bramble-logo-{size}x{size}.png"
    img.save(preview_path)
    print(f"Preview saved: {preview_path}")

    cropped, margin_x, margin_y = symmetric_alpha_crop(img)
    cw, ch = cropped.size
    print(
        f"Cropped {size}x{size} to {cw}x{ch} "
        f"(margins: {margin_x} px x, {margin_y} px y), "
        f"{size * size * 3} -> {cw * ch * 3} bytes"
    )

    rgb565, alpha = rgba_to_rgb565_alpha(cropped)

    out_dir = base / "components" / "ui_graphics" / "assets"
    out_dir.mkdir(parents=True, exist_ok=True)
    write_c_array(
        rgb565, alpha, cw, ch, "img_bramble_logo",
        out_dir / "img_bramble_logo.c", margin_x, margin_y, size,
    )
    write_c_header(
        "img_bramble_logo", out_dir / "img_bramble_logo.h", margin_x, margin_y, size,
    )


if __name__ == "__main__":
    main()
